---
title: "R Notebook"
output: html_notebook
---

```{r ,warning=FALSE, message=FALSE}
library(caret)
library(mlbench)
library(C50)
library(dplyr)
library(plotly)
library(caret)
library(ROSE)
library(rpart)
library(GGally)
```

```{r}
setwd("~/git/projeto-ia/")
```


```{r}
data <- read.csv(("data/true_car_listings.csv"))
```


```{r}

data <- data  %>%
  mutate(Mileage = as.numeric(Mileage)) %>%
  mutate(City = as.numeric(City)) %>%
  mutate(Make = as.numeric(Make)) %>%
  mutate(Model = as.numeric(Model)) %>%
  mutate(State = as.numeric(State)) %>%
  mutate(Vin = as.numeric(Vin)) 

data.correlation %>% 
  na.omit() %>%
  ggcorr(palette = "RdBu",
         color = "grey50",
         label = TRUE, hjust = 1,
         label_size = 3, size = 4,
         nbreaks = 5, layout.exp = 7) +
  ggtitle("Correlation Between Variables")



```



```{r}
index <- createDataPartition(data$Price, p = 0.70, list = FALSE)
data <- data[-index, ]

index <- createDataPartition(data$Price, p = 0.70, list = FALSE)
train <- data[index, ]
test  <- data[-index, ]
```



```{r}
fitControl <- trainControl(
                           method = "repeatedcv", 
                           number = 10,
                           repeats = 5)
```

```{r}
preProcess = c("center", "scale","nzv" )
```

#Lasso
```{r}
model.lasso <- train(Price ~ ., 
               data = train,
               method = "lasso",
               metric = "RMSE",
               preProcess = preProcess,
               trControl = fitControl,
               na.action = na.exclude,
               tuneLength = 10)

model.lasso
```

```{r}
plot(model.lasso, xlab = "Lambda", ylab = "RMSE")
```

```{r}
ggplot(varImp(model.lasso))
```


```{r}
lambda.grid <- expand.grid(lambda = seq(0, 2, by=0.1))
```
#Ridge

```{r}
model.ridge <- train(Price ~ ., 
               data = train,
               method = "ridge", 
               tuneGrid = lambda.grid,
               metric = "RMSE",
               trControl = fitControl, 
               preProcess = preProcess)

model.ridge
```

```{r}
plot(model.ridge, xlab = "Lambda", ylab = "RMSE")
```

```{r}
ggplot(varImp(model.ridge))
```


#KNN

```{r}
model.knn <- train(Price ~ ., 
               data = train,
               trControl = fitControl,
               method = "knn", # pode ser 'lasso'ldf
               metric = "RMSE",
               preProcess = preProcess)

model.knn
```

```{r}
plot(model.knn, ylab = "RMSE")
```

```{r}
ggplot(varImp(model.knn))
```


#Arvore de decisão


```{r Decision Tree, warning=TRUE}
model.dec_tree <- train(Price ~ .,   
                data= train, 
                method = "rpart",
                trControl = fitControl,
                cp=0.001,  
                metric = "RMSE",
                maxdepth=20, 
                linout = TRUE)
model.dec_tree
```

```{r}
plot(model.dec_tree, xlab = "Lambda", ylab = "RMSE")
```

```{r}
ggplot(varImp(model.dec_tree))
```


#RESULTS

#LASSO

```{r}
lasso_prediction <- predict(model.lasso,test)

lasso_data <- data.frame(pred = lasso_prediction, obs = test$Price)

lasso_cv <- round(defaultSummary(lasso_data),digits = 4)

lasso_cv
```


#RIDGE
```{r}
ridge_prediction <- predict(model.ridge,test)

ridge_data <- data.frame(pred = ridge_prediction, obs = test$Price)

ridge_cv <- round(defaultSummary(ridge_data),digits = 4)

ridge_cv
```


#KNN

```{r}
knn_prediction <- predict(model.knn,test)

knn_data <- data.frame(pred = knn_prediction, obs = test$Price)

knn_cv <- round(defaultSummary(knn_data),digits = 4)

knn_cv
```


#DECISION TREE

```{r}
tree_prediction <- predict(model.dec_tree,test)

tree_data <- data.frame(pred = tree_prediction, obs = test$Price)

tree_cv <- round(defaultSummary(tree_data),digits = 4)

tree_cv
```




